// flow-typed signature: 7f860a1441cb803c791bb27fff3372bd
// flow-typed version: <<STUB>>/expo-updates_v~0.2.10/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-updates'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-updates' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-updates/build/ExponentUpdates' {
  declare module.exports: any;
}

declare module 'expo-updates/build/ExponentUpdates.web' {
  declare module.exports: any;
}

declare module 'expo-updates/build/ExpoUpdates' {
  declare module.exports: any;
}

declare module 'expo-updates/build/ExpoUpdates.web' {
  declare module.exports: any;
}

declare module 'expo-updates/build' {
  declare module.exports: any;
}

declare module 'expo-updates/build/Updates.expo' {
  declare module.exports: any;
}

declare module 'expo-updates/build/Updates' {
  declare module.exports: any;
}

declare module 'expo-updates/build/Updates.types' {
  declare module.exports: any;
}

declare module 'expo-updates/scripts/createManifest' {
  declare module.exports: any;
}

declare module 'expo-updates/scripts/filterPlatformAssetScales' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-updates/build/ExponentUpdates.js' {
  declare module.exports: $Exports<'expo-updates/build/ExponentUpdates'>;
}
declare module 'expo-updates/build/ExponentUpdates.web.js' {
  declare module.exports: $Exports<'expo-updates/build/ExponentUpdates.web'>;
}
declare module 'expo-updates/build/ExpoUpdates.js' {
  declare module.exports: $Exports<'expo-updates/build/ExpoUpdates'>;
}
declare module 'expo-updates/build/ExpoUpdates.web.js' {
  declare module.exports: $Exports<'expo-updates/build/ExpoUpdates.web'>;
}
declare module 'expo-updates/build/index' {
  declare module.exports: $Exports<'expo-updates/build'>;
}
declare module 'expo-updates/build/index.js' {
  declare module.exports: $Exports<'expo-updates/build'>;
}
declare module 'expo-updates/build/Updates.expo.js' {
  declare module.exports: $Exports<'expo-updates/build/Updates.expo'>;
}
declare module 'expo-updates/build/Updates.js' {
  declare module.exports: $Exports<'expo-updates/build/Updates'>;
}
declare module 'expo-updates/build/Updates.types.js' {
  declare module.exports: $Exports<'expo-updates/build/Updates.types'>;
}
declare module 'expo-updates/scripts/createManifest.js' {
  declare module.exports: $Exports<'expo-updates/scripts/createManifest'>;
}
declare module 'expo-updates/scripts/filterPlatformAssetScales.js' {
  declare module.exports: $Exports<'expo-updates/scripts/filterPlatformAssetScales'>;
}
