// flow-typed signature: 59776509d270d9c41b85fa5664ef0626
// flow-typed version: <<STUB>>/@expo-google-fonts/inter_v^0.1.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@expo-google-fonts/inter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@expo-google-fonts/inter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@expo-google-fonts/inter/useFonts' {
  declare module.exports: any;
}

// Filename aliases
declare module '@expo-google-fonts/inter/index' {
  declare module.exports: $Exports<'@expo-google-fonts/inter'>;
}
declare module '@expo-google-fonts/inter/index.js' {
  declare module.exports: $Exports<'@expo-google-fonts/inter'>;
}
declare module '@expo-google-fonts/inter/useFonts.js' {
  declare module.exports: $Exports<'@expo-google-fonts/inter/useFonts'>;
}
